"""Shared engineering entry point. Requires Python 3.10+, PowerShell 7 and .NET SDK."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

ENGINEERING = Path(__file__).resolve().parents[1]
DEFAULT_DEPENDENCY_KEY = Path(os.environ.get("MOD_DEPENDENCY_KEY_FILE", str(Path.home() / ".ssh/extension_deploy_ed25519")))


def run(args: list[str], root: Path, *, capture: bool = False) -> str:
    result = subprocess.run(args, cwd=root, check=True, text=True, stdout=subprocess.PIPE if capture else None)
    return result.stdout.strip() if capture else ""


def load(root: Path) -> dict:
    config = json.loads((root / "mod.json").read_text(encoding="utf-8-sig"))
    if config.get("schemaVersion") != 1:
        raise ValueError("Unsupported mod.json schemaVersion")
    for path in [config["project"], *config.get("tests", [])]:
        within(root, path)
    return config


def within(root: Path, path: str) -> Path:
    resolved = (root / path).resolve()
    if not resolved.is_relative_to(root.resolve()):
        raise ValueError(f"Path escapes repository: {path}")
    return resolved


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


def generated(config: dict) -> dict[str, str]:
    files = {name: (ENGINEERING / "config" / name).read_text(encoding="utf-8") for name in ["global.json", ".editorconfig", ".csharpierrc.json", ".csharpierignore"]}
    files[".config/dotnet-tools.json"] = (ENGINEERING / "config/dotnet-tools.json").read_text(encoding="utf-8")
    for command in ["build", "check", "test", "solution", "deploy"]:
        files[f"scripts/{command}.ps1"] = f'''# Generated by ModEngineering. Edit mod.json or the shared implementation.
& python "$PSScriptRoot/../shared/ModEngineering/scripts/mod.py" {command} --repo "$PSScriptRoot/.." @args
if ($LASTEXITCODE -ne 0) {{ throw "ModEngineering {command} failed ($LASTEXITCODE)." }}
'''
    if config["kind"] == "android":
        for name in ["build-release", "sync-dependencies"]:
            files[f"scripts/{name}.ps1"] = f'''# Generated by ModEngineering.
& "$PSScriptRoot/../shared/ModEngineering/scripts/{name}.ps1" -RepositoryRoot "$PSScriptRoot/.." @args
'''
    files["Directory.Build.targets"] = '''<Project>
    <Import Project="$(MSBuildThisFileDirectory)shared/ModEngineering/build/Mod.targets" />
</Project>
'''
    if config.get("engineeringRevision"):
        secret = "\n    secrets:\n      DEPENDENCY_DEPLOY_KEY: ${{ secrets.DEPENDENCY_DEPLOY_KEY }}" if config.get("useExtension") else ""
        files[".github/workflows/build.yml"] = f'''# Generated by ModEngineering.
name: build
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: build-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: ${{{{ !startsWith(github.ref, 'refs/tags/') }}}}
jobs:
  build:
    uses: anosu/ModEngineering/.github/workflows/consumer.yml@{config["engineeringRevision"]}
    with:
      kind: {config["kind"]}
      extension: {str(config.get("useExtension", False)).lower()}{secret}
'''
    if config["kind"] in ("pc", "android"):
        files["build/SharedDependencies.props"] = '''<Project>
    <Import Project="$(ModRepositoryRoot)shared/ModEngineering/build/SharedDependencies.props" />
</Project>
'''
        if config["kind"] == "pc":
            files["build/PcBuild.props"] = '''<Project>
    <Import Project="$(ModRepositoryRoot)shared/ModEngineering/build/PcBuild.props" />
</Project>
'''
        files["SharedDependencies.local.props.example"] = local_props(config)
        projects = [config["project"], *config.get("tests", []), "../Utility/src/Utility/Utility.csproj"]
        if config.get("useExtension"):
            projects.append("../OptionalRuntime/src/Extension/Extension.csproj")
        xml = ET.Element("Solution")
        for path in projects:
            ET.SubElement(xml, "Project", Path=path)
        ET.indent(xml, space="    ")
        files[config["repository"] + ".local.slnx.example"] = ET.tostring(xml, encoding="unicode")
    return files


def local_props(config: dict) -> str:
    extension = "\n        <ExtensionProjectPath>$(MSBuildThisFileDirectory)../OptionalRuntime/src/Extension/Extension.csproj</ExtensionProjectPath>" if config.get("useExtension") else ""
    return f'''<Project>
    <PropertyGroup>
        <SharedDependencyMode>local</SharedDependencyMode>
        <UtilityProjectPath>$(MSBuildThisFileDirectory)../Utility/src/Utility/Utility.csproj</UtilityProjectPath>{extension}
    </PropertyGroup>
</Project>
'''


def solution(root: Path, config: dict, local: bool = False) -> None:
    projects = [config["project"], *config.get("tests", [])]
    if config["kind"] in ("pc", "android"):
        if local:
            values = json.loads(run(["dotnet", "msbuild", config["project"], "-nologo", "-getProperty:UtilityProjectPath,ExtensionProjectPath", "-p:BuildingInsideVisualStudio=false"], root, capture=True))["Properties"]
            projects.append(os.path.relpath(values["UtilityProjectPath"], root).replace("\\", "/"))
            if config.get("useExtension"):
                projects.append(os.path.relpath(values["ExtensionProjectPath"], root).replace("\\", "/"))
        else:
            projects.append("shared/Utility/src/Utility/Utility.csproj")
            if config.get("useExtension"):
                projects.append("shared/Extension/src/Extension/Extension.csproj")
    xml = ET.Element("Solution")
    for project in projects:
        ET.SubElement(xml, "Project", Path=project)
    ET.indent(xml, space="    ")
    write(root / (config["repository"] + (".local" if local else "") + ".slnx"), ET.tostring(xml, encoding="unicode"))


def sync(root: Path, config: dict, check: bool = False) -> None:
    differences = []
    for name, text in generated(config).items():
        path = root / name
        expected = text.rstrip() + "\n"
        if not path.exists() or path.read_text(encoding="utf-8-sig") != expected:
            differences.append(name)
            if not check:
                write(path, expected)
    if check and differences:
        raise ValueError("Generated configuration drift: " + ", ".join(differences) + ". Run mod.py sync.")
    if not check:
        solution(root, config)


def build(root: Path, config: dict, configuration: str) -> None:
    run(["dotnet", "build", config["project"], "-c", configuration, "--nologo"], root)


def test(root: Path, config: dict, configuration: str) -> None:
    for project in config.get("tests", []):
        run(["dotnet", "test", project, "-c", configuration, "--nologo"], root)


def deploy(root: Path, config: dict, configuration: str) -> None:
    if config["kind"] != "pc":
        raise ValueError("deploy is only supported for PC Mods")
    build(root, config, configuration)
    values = json.loads(run(["dotnet", "msbuild", config["project"], "-nologo", "-getProperty:GameDir,TargetDir", f"-p:Configuration={configuration}"], root, capture=True))["Properties"]
    if not values["GameDir"]:
        raise ValueError("Set GameDir in Build.local.props before deploying")
    game = Path(values["GameDir"]).resolve()
    destination = within(game, config["deployDirectory"].replace("{configuration}", configuration))
    destination.mkdir(parents=True, exist_ok=True)
    for name in [config["assembly"] + ".dll", "Utility.dll"]:
        shutil.copy2(Path(values["TargetDir"]) / name, destination / name)
    print(f"Deployed to {destination}")


def extension_secret(root: Path, key: Path) -> None:
    config = load(root)
    if not config.get("useExtension"):
        raise ValueError("This repository does not use Extension")
    key = key.resolve(strict=True)
    if key.is_relative_to(root) or key.is_relative_to(ENGINEERING):
        raise ValueError("Store the private key outside source repositories")
    # gh reads stdin directly; never capture or print private key bytes.
    with key.open("rb") as stream:
        subprocess.run(["gh", "secret", "set", "DEPENDENCY_DEPLOY_KEY", "--repo", config["github"]], stdin=stream, check=True)


def update(root: Path, revision: str, dependency: str = "ModEngineering") -> None:
    if run(["git", "status", "--porcelain"], root, capture=True):
        raise ValueError(f"Refusing to upgrade a dirty repository: {root}")
    shared = root / "shared" / dependency
    run(["git", "fetch", "origin"], shared)
    run(["git", "checkout", "--detach", revision], shared)
    run(["git", "submodule", "update", "--init", "--recursive"], shared)
    config = load(root)
    if dependency == "ModEngineering":
        config["engineeringRevision"] = run(["git", "rev-parse", "HEAD"], shared, capture=True)
        write(root / "mod.json", json.dumps(config, indent=2, ensure_ascii=False))
    # Run the newly selected implementation, not the old caller.
    entry = root / "shared/ModEngineering/scripts/mod.py"
    run([sys.executable, str(entry), "sync", "--repo", str(root)], root)
    run([sys.executable, str(entry), "check", "--repo", str(root)], root)
    run([sys.executable, str(entry), "test", "--repo", str(root)], root)
    config = load(root)
    if config["kind"] == "android":
        run(["pwsh", "-NoProfile", "-File", "scripts/build-release.ps1"], root)
    else:
        run(["dotnet", "build", config["project"], "-c", "Release", "-p:UsePinnedSharedDependencies=true", "--nologo"], root)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["sync", "check", "build", "test", "solution", "deploy", "extension-secret", "update"])
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--configuration", default="Release", choices=["Debug", "Release"])
    parser.add_argument("--local", action="store_true")
    parser.add_argument("--key", type=Path, default=DEFAULT_DEPENDENCY_KEY)
    parser.add_argument("--revision")
    parser.add_argument("--dependency", choices=["ModEngineering", "Utility", "Extension"], default="ModEngineering")
    args = parser.parse_args()
    root = args.repo.resolve()
    config = load(root)
    if args.command == "sync":
        sync(root, config)
    elif args.command == "check":
        sync(root, config, check=True)
        actual = run(["git", "rev-parse", "HEAD"], root / "shared/ModEngineering", capture=True)
        if actual != config.get("engineeringRevision"):
            raise ValueError("Engineering submodule and workflow revisions differ; run the shared upgrade command")
        for project in [config["project"], *config.get("tests", [])]:
            if not within(root, project).is_file():
                raise ValueError("Configured project is missing: " + project)
        run(["dotnet", "tool", "restore"], root)
        run(["dotnet", "tool", "run", "csharpier", "check", "."], root)
    elif args.command == "build":
        build(root, config, args.configuration)
    elif args.command == "test":
        test(root, config, args.configuration)
    elif args.command == "solution":
        solution(root, config, args.local)
    elif args.command == "deploy":
        deploy(root, config, args.configuration)
    elif args.command == "extension-secret":
        if not args.key:
            parser.error("extension-secret requires --key")
        extension_secret(root, args.key)
    elif args.command == "update":
        if not args.revision:
            parser.error("update requires --revision (immutable tag or commit)")
        update(root, args.revision, args.dependency)


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        sys.exit(str(error))
